# Generated by Django 5.1.15 on 2026-03-30 16:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='image',
            field=wagtail.fields.StreamField([('image', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {'help_text': 'Image with contextual alt text support.'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override alt text for this usage (optional).', 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Mark as decorative (no alt text).', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('alt_override', 1), ('is_decorative', 2), ('caption', 3)]], {})}),
        ),
    ]
